<?php

return [
    'permissions' => [
        'root' => ['root', 'vendor', 'admin', 'store'],

        'pos.index' => ['store'],
        'pos.store' => ['store'],
        'pos.update' => ['store'],
        'pos.sales' => ['store'],
        'pos.payment' => ['store'],
        'pos.customerStore' => ['store'],
        'pos.order.show' => ['store'],
        'pos.fetch.variants' => ['store'],
        'pos.fetch.products' => ['store'],

        'service.index' => ['root', 'store', 'vendor'],
        'service.create' => ['root'],
        'service.store' => ['root'],
        'service.edit' => ['root'],
        'service.update' => ['root'],
        'service.status.toggle' => ['root'],

        'additional.index' => ['root', 'store'],
        'additional.create' => ['root', 'store'],
        'additional.store' => ['root', 'store'],
        'additional.edit' => ['root', 'store'],
        'additional.update' => ['root', 'store'],
        'additional.status.toggle' => ['root', 'store'],

        'variant.index' => ['root', 'store'],
        'variant.update' => ['root', 'store'],
        'variant.create' => ['store'],
        'variant.store' => ['store'],
        'variant.products' => ['root', 'store'],

        'subscription.index' => ['root','admin'],
        'subscription.report' => ['root','admin','store'],
        'subscription.status.chanage' => ['root','admin'],
        'subscription.store' => ['root','admin'],
        'subscription.update' => ['root','admin'],
        'subscription.purchase.index' => ['store'],
        'subscription.purchase.update' => ['store'],

        'notification.index' => ['root'],
        'notification.send' => ['root'],

        'customer.index' => ['root'],
        'customer.show' => ['root'],
        'customer.create' => ['root'],
        'customer.store' => ['root'],
        'customer.edit' => ['root'],
        'customer.update' => ['root'],
        'customer.change.password' => ['root'],
        'customer.update.password' => ['root'],

        'driver.assign' => ['store'],
        'driver.status.toggle' => ['store'],

        'product.index' => ['root', 'store'],
        'product.create' => ['store'],
        'product.store' => ['store'],
        'product.show' => ['root', 'store'],
        'product.edit' => ['root', 'store'],
        'product.update' => ['root', 'store'],
        'product.status.toggle' => ['root', 'store'],

        'banner.index' => ['root'],
        'banner.promotional' => ['root'],
        'banner.store' => ['root'],
        'banner.edit' => ['root'],
        'banner.update' => ['root'],
        'banner.destroy' => ['root'],
        'banner.status.toggle' => ['root'],

        'order.index' => ['root', 'store', 'vendor'],
        'order.show' => ['root', 'store'],
        'order.edit' => ['root', 'store'],
        'order.status.change' => ['store'],
        'order.print.labels' => ['root', 'store'],
        'order.print.invioce' => ['root', 'store'],
        'orderIncomplete.index' => ['root', 'store'],
        'orderIncomplete.paid' => ['root', 'store'],

        'revenue.index' => ['root', 'store', 'vendor'],
        'revenue.generate.pdf' => ['root', 'store'],
        'report.generate.pdf' => ['root', 'store'],

        'coupon.index' => ['root', 'store'],
        'coupon.create' => ['store'],
        'coupon.store' => ['store'],
        'coupon.edit' => ['root', 'store'],
        'coupon.update' => ['root', 'store'],

        'contact' => ['root'],

        'driver.index' => ['root', 'store'],
        'driver.create' => ['store'],
        'driver.store' => ['store'],
        'driverAssign' => ['root', 'store'],
        'driver.details' => ['root', 'store'],

        'profile.index' => ['root', 'vendor'],
        'profile.update' => ['root', 'vendor'],
        'profile.edit' => ['root', 'vendor'],
        'profile.change-password' => ['root', 'vendor'],

        'schedule.index' => ['root', 'store'],
        'toggole.status.update' => ['root', 'store'],
        'schedule.update' => ['root', 'store'],

        'dashboard.calculation' => ['root', 'store'],
        'dashboard.revenue' => ['root', 'store'],
        'dashboard.overview' => ['root', 'store'],

        'setting.show' => ['root'],
        'setting.edit' => ['root'],
        'setting.update' => ['root'],

        'vendor.index' => ['root'],
        'vendor.create' => ['root'],
        'vendor.store' => ['root'],
        'vendor.edit' => ['root'],
        'vendor.update' => ['root'],
        'vendor.delete' => ['root'],
        'vendor.wallet' => ['root'],
        'vendor.shop' => ['root'],
        'vendor.shop.transaction' => ['root'],
        'vendor.status.toggle' => ['root'],
        'vendor.shop.details' => ['root'],
        'vendor.commissionUpdate' => ['root'],

        'shop.index' => ['root'],
        'shop.create' => ['root'],
        'shop.store' => ['root'],
        'shop.edit' => ['root'],
        'shop.update' => ['root'],
        'shop.delete' => ['root'],
        'shop.wallet' => ['root'],
        'shop.transaction' => ['root'],
        'shop.order' => ['root'],
        'shop.status.toggle' => ['root'],
        'shop.show' => ['root'],
        'shoplist.index' => ['root'],
        'shoplist.details' => ['root'],
        'shop.service' => ['root'],
        'shop.service.update' => ['root'],
        'shop.product' => ['root'],
        'shop.product.approve' => ['root'],
        'shop.variant' => ['root'],
        'shop.variant.approve' => ['root'],
        'shop.commissionUpdate' => ['root'],
        'shoplist.index' => ['vendor', 'root'],
        'shoplist.details' => ['vendor', 'root'],
        'shop.generateReport' => ['vendor', 'root'],
        'shop.order.export' => ['vendor', 'root'],
        'shop.store.export' => ['vendor', 'root'],

        'wallet.index' => ['vendor', 'store'],
        'wallet.store' => [],
        'wallet.update' => ['root', 'vendor'],
        'wallet.transction' => ['vendor', 'store'],
        'wallet.withdraw' => ['vendor', 'store'],

        'store.location-update' => ['vendor', 'store', 'root'],

        'store.index' => ['store'],
        'store.edit' => ['store'],
        'store.update' => ['store'],
        'store.user.update' => ['store'],
        'store.address' => ['store', 'root'],
        'store.address.update' => ['store', 'root', 'admin'],

        'shops.map-view' => ['vendor', 'admin', 'root'],

        'invoiceManage.index' => ['root', 'admin', 'store'],
        'invoiceManage.update' => ['root', 'admin', 'store'],
        'invoiceManage.preview' => ['root', 'admin', 'store'],
        'invoiceManage.pdfUpdate' => ['root', 'admin', 'store'],

        'language.index' => ['root', 'admin', 'store'],
        'language.edit' => ['root', 'admin', 'store'],
        'language.update' => ['root', 'admin', 'store'],
        'language.delete' => ['root', 'admin', 'store'],

        'checkout' => ['customer'],
        'orders-web' => ['customer'],
        'pick-schedule' => ['customer'],
        'delivery-schedule' => ['customer'],
        'order-details' => ['customer'],
        'order-detail' => ['customer'],
        'my-dashboard' => ['customer'],
        'my-orders' => ['customer'],
        'delivery-address' => ['customer'],
        'manage-addresses' => ['customer'],
        'delivery-address-update' => ['customer'],
        'default-address' => ['customer'],
        'delete-address' => ['customer'],
        'favourite-store' => ['customer'],
        'my-favourite' => ['customer'],
        'my-settings' => ['customer'],
        'promotion-notify' => ['customer'],
        'order-update-notify' => ['customer'],
        'update-user' => ['customer'],
        'order.invioce' => ['customer'],
        'logout-web' => ['customer']
    ],
];
